package org.panda.resource;

import org.panda.utility.ArrayUtil;
import org.panda.utility.CollectionUtil;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.*;

/**
 * Generated by Deep Research feature of Gemini 2.5
 * @author Ozgun Babur
 */
public class GeminiLungCancerGenes extends FileServer
{
	private static GeminiLungCancerGenes instance;

	private Set<String> cancerGenes;
	private Set<String> oncogenes;
	private Set<String> tumorSuppressors;

	public static synchronized GeminiLungCancerGenes get()
	{
		if (instance == null) instance = new GeminiLungCancerGenes();
		return instance;
	}

	public Set<String> getAllSymbols()
	{
		return cancerGenes;
	}

	public Set<String> getCancerGenes()
	{
		return cancerGenes;
	}

	public boolean isCancerGene(String sym)
	{
		return cancerGenes.contains(sym);
	}

	public boolean isOncogene(String sym)
	{
		return oncogenes.contains(sym);
	}

	public boolean isOncogeneOnly(String sym)
	{
		return isOncogene(sym) && !isTumorSuppressor(sym);
	}

	public boolean isTumorSuppressor(String sym)
	{
		return tumorSuppressors.contains(sym);
	}

	public boolean isTumorSuppressorOnly(String sym)
	{
		return isTumorSuppressor(sym) && !isOncogene(sym);
	}

	public Set<String> getOncogenes()
	{
		return this.oncogenes;
	}

	public Set<String> getTumorSuppressors()
	{
		return this.tumorSuppressors;
	}

	@Override
	public String[] getLocalFilenames()
	{
		return new String[]{"Gemini-lung-cancer-genes.tsv"};
	}

	@Override
	public boolean load() throws IOException
	{
		cancerGenes = new HashSet<>();
		oncogenes = new HashSet<>();
		tumorSuppressors = new HashSet<>();

		getResourceAsStream(getLocalFilenames()[0]).skip(1).map(l -> l.split("\t")).forEach(t ->
		{
			String symbol = t[0].split(" ")[0];
			cancerGenes.add(symbol);
			if (t[1].startsWith("O")) oncogenes.add(symbol);
			else if (t[1].startsWith("T")) tumorSuppressors.add(symbol);
		});

		return true;
	}


	public static void main(String[] args) throws IOException
	{
		CollectionUtil.printVennCounts(get().oncogenes, get().tumorSuppressors);
//		writeHighlightFile("/Users/ozgun/Documents/Analyses/CPTAC-LSCC-3.2/oncokb.highlight");
	}

	private static void writeHighlightFile(String file) throws IOException
	{
		BufferedWriter writer = Files.newBufferedWriter(Paths.get(file));

		for (String sym : get().getCancerGenes())
		{
			writer.write("node\t" + sym + "\n");
		}

		writer.close();
	}
}
